server:
  port: 8080

spring:
  application:
    name: inventoryservice

  cloud:
    config:
      profile: prod

  kubernetes:
    discovery:
      enabled: true
      all-namespaces: true

  discovery:
    client:
      health-indicator:
        enabled: false

  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}

  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      platform: mysql
      mode: always
