apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service-app
spec:
  selector:
    matchLabels:
      app: inventory-service-app
  template:
    metadata:
      labels:
        app: inventory-service-app
    spec:
      containers:
      - name: inventory-service-app
        image: IMAGE_URL/inventoryservice
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: config-cm
              key: CONFIG_URL
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-cm
              key: HOSTNAME
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: common-cm
              key: SPRING_PROFILES_ACTIVE

---

apiVersion: v1
kind: Service
metadata:
  name: inventory-service-svc
spec:
  selector:
    app: inventory-service-app
  ports:
  - port: 80
    targetPort: 8080
